import smtplib
from email.message import EmailMessage
import os
import sys

def send_procurement_report(
    smtp_server: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    recipient_email: str,
    subject: str,
    body: str,
    report_path: str
):
    # Create the email
    msg = EmailMessage()
    msg["From"] = smtp_user
    msg["To"] = recipient_email
    msg["Subject"] = subject
    msg.set_content(body)

    # Attach the report file
    with open(report_path, "rb") as f:
        file_data = f.read()
        file_name = os.path.basename(report_path)

    msg.add_attachment(file_data, maintype="application", subtype="octet-stream", filename=file_name)

    # Send the email
    with smtplib.SMTP(smtp_server, smtp_port) as smtp:
        smtp.starttls()  # secure connection
        smtp.login(smtp_user, smtp_password)
        smtp.send_message(msg)

    print(f"✅ Email sent to {recipient_email} with attachment {file_name}!")


if __name__ == "__main__":
    # Example usage — set these via environment variables
    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587
    SMTP_USER = os.environ.get("SMTP_USER")  # your email address
    SMTP_PASS = os.environ.get("SMTP_PASS")  # your email password or app password

    TO_EMAIL = sys.argv[1] if len(sys.argv) > 1 else "recipient@example.com"

    # Report file you want to send
    REPORT_PATH = "reports/final_procurement_summary.csv"

    # Email content
    SUBJECT = "APIS Procurement Summary Report"
    BODY = """
Hello,

Please find the attached procurement summary report generated by APIS.

Best regards,
APIS System
"""

    send_procurement_report(
        SMTP_SERVER,
        SMTP_PORT,
        SMTP_USER,
        SMTP_PASS,
        TO_EMAIL,
        SUBJECT,
        BODY,
        REPORT_PATH
    )
